### ISSUE TITLE
not work in android

### ISSUE THREAD

**Issue by htetwaiyan** [saturngod/flutter_mdetect#1]
always show zawgyi

**Comment by saturngod** [comment]
what phone are you using ? I am testing with Pixel Emulator, it's showing unicode.

![](https://dsc.cloud/ClientsTimeline/Screen-Shot-2020-04-25-at-3.18.51-AM.png)
![](https://dsh.re/8395a)
![](https://dsh.re/2f1c8)

**Comment by saturngod** [comment]
Tested on Zawgyi phone (Meizu M5) and it's showing Zawgyi.

So, it's not issue of my code and close the issue.

![](https://dsh.re/9a215)

**Comment by htetwaiyan** [comment]
I really don’t know. I think that cause of my flutter version. In all my phone, this package is not work even Iphone.
![554222DA-796F-4BDC-A5A4-7A9636AAFB80](https://user-images.githubusercontent.com/25844134/80263066-777b6700-86b5-11ea-87ce-48a2f8a6deb5.jpeg)

**Comment by saturngod** [comment]
What is your flutter version ? Are you using latest flutter ? What is the iOS version that you test ?

**Comment by htetwaiyan** [comment]
All versions are the latest. I tested 4 android devices. When I changed zawgyi-><-unicode in settings, the Mdetect package always show true.

**Comment by saturngod** [comment]
After changing , did you need  close the app and reopen the app ?

**Comment by saturngod** [comment]
@htetwaiyan  , can you download and test https://dsh.re/dbc5b
